### PR TITLE
SR-11 add google login test page

### PR DESCRIPTION
**Pull request by Bravo555**
The commit introduces a test /login page with nothing but "sign in with google" widget on it. It can be viewed by clicking the "Login" link in the index page.

The google client id is fine to include in source code as is, and according to [create react app docs] we can't really use any secrets in the frontend anyway, as it will be included in the build and set to the client.

[create react app docs]: https://create-react-app.dev/docs/adding-custom-environment-variables/

The current sign-in flow looks like this:

1. Navigate to the login page. The "Sign in with Google" widget should appear:
image
2. Input your Google credentials in the popup window
image
3. There should be a following message in the console:
image
4. After page refresh, the popup should display that user is logged in:
image

Reviewers are asked to confirm that login flow works as described above.
As for the PR, the functionality is not complete, so I will be marking it as draft, and adding more commits to it, and we will merge this feature when we're sure it works as intended. In the meantime, this can be a place for discussion of the feature. 

I would like your feedback regarding:
- how we want our sign-in flow to look like
- what information about the user do we want to obtain from user's google account
- how do we want to authorize actions a user can take in the application
- and any other ideas you might have

### CODE REVIEW

**Comment by Bravo555** [comment]
The Google sign in doesn't seem to work on Netlify preview for now, looking to see if it can be fixed. Also regarding the preview, remember that in React, when using `BrowserRouter` (which I do), there can be errors if you do full refresh on any page that is not the root `/`, eg. `/login`. To make a refresh, you need to go to the root page and then use the link to go back to the login page, as annoying as it is.

**Comment by Bravo555** [comment]
> ... regarding the preview, remember that in React, when using `BrowserRouter` (which I do), there can be errors if you do full refresh on any page that is not the root `/`, eg. `/login`. To make a refresh, you need to go to the root page and then use the link to go back to the login page, as annoying as it is.

Managed to fix the issue by using a [request rewrite](https://docs.netlify.com/routing/redirects/rewrites-proxies/#limitations).

**Comment by Mendrejk** [comment]
Marcel, SR-11 is about the implementation of backend endpoints for OAauth2

**Comment by Bravo555** [comment]
Whoops, my bad then. I don't have much experience in OAuth, so I kinda approached it from the end user perspective, but I'll switch my focus to OAuth then. But given how we'll have to do Google login eventually, can we also introduce it in this PR or would that be a problem?

**Comment by Mendrejk** [comment]
@deamacto I would probably have Marcel create another PR and work on both of those. But it's your call.

**Pull request closed without merging**
