### PR TITLE
SR-21 Add the top banner component

### PR DESCRIPTION
**Pull request by kanapka0**

### CODE REVIEW

**Review by Mario-659 — CHANGES_REQUESTED** [review]
Add `fortawesome` to dependencies in package.json

**Review by Bravo555 — CHANGES_REQUESTED** [review]
Can you add the banner to the index page so we can see how it looks like in the preview?

Also, just keep in mind:
- For future reference, avoid adding dead code; there's no reason to have code that isn't used anywhere, so if you make a new component, put it somewhere where we can see it on preview at least, even if its location will have to be moved in the future
- As you have multiple commits with the same name that collectively add only one feature, when merging be sure to use the squash option to squash all these commits into one.

**Comment by Mendrejk** [comment]
Regarding what @Bravo555 said, you should always use squash & merge when merging into dev. Generally you should squash all commits into one unless there are multiple distinctive functionalities added with one PR (but generally that should not be the case). You can keep the default squashed commit description and use the PR title as the commit message (so just use the defaults).

**Review by Mendrejk — APPROVED** [review]
Ship It!

**Review by Bravo555 — APPROVED** [review]

**Review by Mario-659 — APPROVED** [review]

**Pull request merged**
