### PR TITLE
SR-54 Introduce question sets

### PR DESCRIPTION
**Pull request by Mendrejk**
A question set is a generated set of questions with given total time and avg difficulty (can vary +- 1 with, for now, 1 : 4 : 1 distribution for one_lower : chosen : one_higher)

### CODE REVIEW

**Comment by Mario-659** [comment]
This PR is very messy.

1. I don't know what is idea behind those `question sets`. There is no explanation either here or on jira. Why is it needed?
2. I can't see the page on netify, don't know what this page should do, didn't see any mockup
3. Test CL is failing (!!!)
4. Comments with TODO might be controversial but comments with warning about spaghetti code are not acceptable
5. Why are you changing formatting of gradle file? I know you applied some automatic formatting but it introduces more confusion and it's not like this is better now - it's just different convention
6. Commit `Fix a bunch of stuff` - ok, but which stuff? You should give more explanation in this longer commit message (I don't know what is it called - the one that you can expand with three dots on github)
7. You added `QuestionSetDTO` - ok but know there is just one DTO. We should have DTO for every class or no DTO at all
8. Same with Spring Validation. You added Validation to QuestionSet - what about other entities?

This is all just from the first look. I know that you want to make it before deadline but this PR introduces a lot of rework for later and I don't even know what it should be about

**Review by Mario-659 — CHANGES_REQUESTED** [review]
This PR is very messy.

1. I don't know what is the idea behind those `question sets`. There is no explanation either here or on jira. Why is it needed?
2. I can't see the page on netify, don't know what this page should do, didn't see any mockup
3. Test CL is failing (!!!)
4. Comments with TODO might be controversial but comments with warning about spaghetti code are not acceptable
5. Why are you changing formatting of gradle file? I know you applied some automatic formatting but it introduces more confusion and it's not like this is better now - it's just different convention
6. Commit `Fix a bunch of stuff` - ok, but which stuff? You should give more explanation in this longer commit message (I don't know what is it called - the one that you can expand with three dots on github)
7. You added `QuestionSetDTO` - ok but now there is just one DTO. We should have DTO for every class or no DTO at all
8. Same with Spring Validation. You added Validation to QuestionSet - what about other entities?

This is all just from the first look. I know that you want to make it before deadline but this PR introduces a lot of rework for later and I don't even know what it should be about

**Comment by FilipJQ77** [comment]
The questions sets are needed for the actual recruitment sessions that we will do soon, because without it this is only a nicer question list.
Though I agree with your other points. I think maybe we should only use this version in the next few days as it would help a lot with the recruitment process, and perhaps make it better/different another time (so this version would not be 'official')

What do you guys think about it? @Mendrejk @Mario-659

**Comment by Mario-659** [comment]
If it works and it's needed for recruitment then we can use that. Just make sure this is fully tested - I'm sure there are some bugs right now. Also add some explanation, screenshot of the question set page to jira / here.

What about creating new temporary branch for release, merging to that, deleting that branch after recruitment and adding this feature to dev when we will have more time?

**Comment by Mendrejk** [comment]
Sounds good, I'll set up a temporary branch and after the recruitment we can see about fixing this change and getting it into dev

**Pull request closed without merging**
