### PR TITLE
SR-26 Add login page (again)

### PR DESCRIPTION
**Pull request by Bravo555**
Reopen old PR with login page, with a better idea how it works this time.

After logging in, the page should console.log the JWT token:
JWT token

The token can then be analysed at https://jwt.io and shall be used in all requests to the backend:
image

### CODE REVIEW

**Comment by Mendrejk** [comment]
Looking good 😄

**Review by Mario-659 — DISMISSED** [review]

**Comment by Mendrejk** [comment]
https://developers.google.com/identity/sign-in/web/build-button - look here for styling the log in with Google button

**Comment by Bravo555** [comment]
https://developers.google.com/identity/gsi/web/guides/overview#user_sign-in_to_your_site
https://developers.google.com/identity/gsi/web/guides/verify-google-id-token

**Comment by Bravo555** [comment]
> https://developers.google.com/identity/sign-in/web/build-button - look here for styling the log in with Google button

This refers to an older, discontinued platform. Here is the newer platform and it's customization capabilities are very limited.
https://developers.google.com/identity/gsi/web/reference/html-reference#visual-attributes

Additionally, looks like the current button design violates [Google Sign-In Branding Guidelines](https://developers.google.com/identity/branding-guidelines). Google requires the use of Roboto Medium font, but the mockup uses a different font.

For now I'll try customising it using the provided customisation options to make it look kinda like the mockup, but I don't think exact parity is possible.

**Comment by Bravo555** [comment]
This is how it looks now.

image

- Width is limited by the library to 400px. I think it's because at this font size, the gaps on the sides would be too big. Looks good enough to me.
- Colour also limited by the library, looks like the "light feel" we were going for in the mockup is incompatible with Google design guidelines, with Roboto font it would look kinda off

**Comment by Bravo555** [comment]
The layout breaks on mobile, will undraft again when fixed

**Comment by Mario-659** [comment]
Look at PR #15. Make question component also breaks on mobile. I think we decided to not include mobile in MVP so this is fine

**Comment by Bravo555** [comment]
Looks to me like the case of Google sign-in library being bad at the only thing it's supposed to be good at, which is rendering the sign-in button, having very limited responsiveness capabilities. I have found similar sentiment on Stackoverflow.

This is how the 400px width button looks like on a mobile layout:
image

Default smaller size by comparison:
image

I think for the sake of not breaking the layout on mobile, we should use the smaller button as a workaround, and figure out the proper fix later.

**Comment by Bravo555** [comment]
> Look at PR #15. Make question component also breaks on mobile. I think we decided to not include mobile in MVP so this is fine
TailwindCSS's philosophy is mobile-first. If we ignore mobile now, then we will be just rewriting a lot of CSS later, when we can just do it correctly now with little extra effort. I guess we should talk about that during the meeting.

**Review by Mario-659 — APPROVED** [review]

**Review by Mendrejk — APPROVED** [review]
Ship It!

**Pull request merged**
