### PR TITLE
Add login fail message

### PR DESCRIPTION
**Pull request by Bravo555**
The message informs the user that they're not registered in the Recruitment System.

### CODE REVIEW

**Comment by Bravo555** [comment]
How it looks now
image

**Comment by Bravo555** [comment]
If not all accounts in `student.pwr.edu.pl` domain are able to login, I will need a server-side endpoint whose purpose is not to expose any resource, but just to tell the client if they're registered or not. After obtaining JWT from Google, I will hit that endpoint and display the message accordingly. Will be done in #25, this one is ready to be merged.

**Comment by Mario-659** [comment]
Spring will return 403 code if (and only if) jwt token is valid but user is not registered (email not in database). You can just ping server with any get request after obtaining token and display message based on response code.

**Review by Mario-659 — APPROVED** [review]

**Review by Mendrejk — APPROVED** [review]
Ship It!

**Pull request merged**
